version: "3.4"
services:
 app:
   image: procorp_docker
   container_name: procorp_docker
   entrypoint: /bin/sh
   build:
      context: .
      target: builder
   ports:
     - 8000:8000
   working_dir: /src/app
   volumes:
     - type: bind
       source: ./
       target: /src/app
   tty: true